version: '3.8'
services:
  server:
    container_name: container-servidor
    build: 
      context: "./backend"
    ports:
      - "3001:3001"
    command: npm run dev
  client:
    container_name: container-front
    build: 
      context: "./frontend"
    ports:
      - "3000:3000"
    command: npm run start
